/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ALayout: typeof import('antdv-next')['Layout']
    ALayoutContent: typeof import('antdv-next')['LayoutContent']
    ALayoutFooter: typeof import('antdv-next')['LayoutFooter']
    ALayoutHeader: typeof import('antdv-next')['LayoutHeader']
    ASplitter: typeof import('antdv-next')['Splitter']
    ASplitterPanel: typeof import('antdv-next')['SplitterPanel']
    ConnectionStatus: typeof import('./src/components/ConnectionStatus.vue')['default']
    OnlineUsers: typeof import('./src/components/OnlineUsers.vue')['default']
    RemoteCursors: typeof import('./src/components/RemoteCursors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
