/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ConnectionStatus: typeof import('./components/ConnectionStatus.vue')['default']
    OnlineUsers: typeof import('./components/OnlineUsers.vue')['default']
    RemoteCursors: typeof import('./components/RemoteCursors.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
